name: mini_library
description: A mini library app for reading and borrowing books.

# The following defines the version and build number for your application.
version: 1.0.0+1

# Specify the environment for the app
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 # State management for MVVM architecture
  sqflite: ^2.4.1 # SQLite database for CRUD operations
  path: 1.9.0 # Helper library to manage file paths
  google_fonts: ^4.0.3 # For custom fonts
  fluttertoast: ^8.2.1 # For showing toast messages (e.g., success notifications)
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For Flutter web apps to include fonts
flutter:
  uses-material-design: true

  # Define assets (e.g., images or database files)
  assets:
    - assets/images/ # Directory for book cover images
    - assets/fonts/ # Directory for custom fonts (optional)

  # Optionally define fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/static/Roboto-Regular.ttf
        - asset: assets/fonts/static/Roboto-Bold.ttf
          weight: 700
